<a href="https://colab.research.google.com/github/Maria-Vereina/LAB/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Лабораторная работа № 1 NumPy**

In [2]:
import numpy as np
import timeit
import time

**1.1.** Считайте число n. Создайте в переменной Z Numpy вектор из нулей длины n.

**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

In [ ]:
#способ 1 - с NumPy
n = int(input())
Z = np.zeros(n)
Z

5


array([0., 0., 0., 0., 0.])

In [ ]:
#способ 2 - без NumPy
Z = ''
n = int(input())
Z += '['
while n > 0:
  Z += '0. '
  n -= 1
Z = Z[0:-1]
Z += ']'
Z

5


'[0. 0. 0. 0. 0.]'

In [ ]:
def with_n(n):
  Z = np.zeros(n)
  return Z


def without_n(n):
  Z = ''
  Z += '['
  while n > 0:
    Z += '0. '
    n -= 1
  Z = Z[0:-1]
  Z += ']'
  return Z


if __name__ == '__main__':
  start_time = timeit.default_timer()
  with_n(n)
  range_time_1 = timeit.default_timer() - start_time

  start_time = timeit.default_timer()
  without_n(n)
  arange_time_1 = timeit.default_timer() - start_time

print(f' время работы решения задачи с numpy: {range_time_1}')
print(f' время работы решения задачи без numpy: {arange_time_1}')

 время работы решения задачи с numpy: 1.451600019208854e-05
 время работы решения задачи без numpy: 3.3000001167238224e-06


**1.2.** Посчитайте размер матрицы Z в байтах и выведите его на печать.

In [ ]:
#способ 1
Z=np.zeros((10,10))
print(Z.nbytes)

800


In [ ]:
#cпособ 2
Z=np.zeros((10,10))
print(Z.itemsize*Z.size)

800


In [ ]:
def sposob1():
  Z=np.zeros((10,10))
  print(Z.nbytes)

def sposob2():
  Z=np.zeros((10,10))
  print(Z.itemsize*Z.size)

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time

  start_time = timeit.default_timer()
  sposob2()
  arange_time_1 = timeit.default_timer() - start_time

print(f' время работы решения способом 1: {range_time_1}')
print(f' время работы решения cпособом 2: {arange_time_1}')

800
800
 время работы решения способом 1: 0.0009337440001218056
 время работы решения cпособом 2: 0.0005201660001148412


In [ ]:
#cпособ 1
Z = np.array([1, 2, 3], dtype=np.float64)
print(Z.nbytes)

24


In [ ]:
#cпособ 2
Z = np.array([1, 2, 3], dtype=np.float64)
print(Z.itemsize*Z.size)

24


In [ ]:
def sposob1():
  Z = np.array([1, 2, 3], dtype=np.float64)
  print(Z.nbytes)

def sposob2():
  Z = np.array([1, 2, 3], dtype=np.float64)
  print(Z.itemsize*Z.size)

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time

  start_time = timeit.default_timer()
  sposob2()
  arange_time_1 = timeit.default_timer() - start_time

print(f' время работы решения способом 1: {range_time_1}')
print(f' время работы решения cпособом 2: {arange_time_1}')

24
24
 время работы решения способом 1: 0.0009087969999654888
 время работы решения cпособом 2: 0.0003141760000744398


**1.3.** Считайте 2 числа:


*   n - размер Numpy вектора
*   x - координата элемента вектора, который должен быть равен 1.

Остальные элементы вектора
должны быть равны 0. Сохраните вектор в переменную Z.

**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

In [ ]:
#способ 1
n=int(input())
x=int(input())
Z = np.zeros(n)
Z[x-1]=1
Z

10
4


array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [ ]:
#способ 2
n=int(input())
x=int(input())
Z = np.zeros(n-1)
Z = np.insert(Z, x-1, 1)
Z

10
4


array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [ ]:
n=int(input())
x=int(input())

def sposob1():
  Z = np.zeros(n)
  Z[x-1]=1
  Z

def sposob2():
  Z = np.zeros(n-1)
  Z = np.insert(Z, x-1, 1)
  Z

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time

  start_time = timeit.default_timer()
  sposob2()
  arange_time_1 = timeit.default_timer() - start_time

print(f' время работы решения способом 1: {range_time_1}')
print(f' время работы решения cпособом 2: {arange_time_1}')

10
4
 время работы решения способом 1: 2.6703000003180932e-05
 время работы решения cпособом 2: 0.00012838600014219992


**1.4**. Считайте 2 числа n, m. Создайте вектор Z состоящий из чисел от n до m с шагом 1.

**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

In [ ]:
#способ 1
n=int(input())
m=int(input())
Z = np.arange(n, m+1, 1)
Z

10
50


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
n=int(input())
m=int(input())

def sposob1():
  Z = np.arange(n, m+1, 1)
  Z

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

10
50
 время работы решения способом 1: 4.694699964602478e-05


**1.5**. Дан вектор Z. "Разверните" его

**Примечание**. В этой задаче не нужно ничего выводить на печать или считывать. Только
развернуть уже созданный вектор Z.


In [17]:
Z = np.array([1, 2, 3, 4])
Z = Z[::-1]
Z

array([4, 3, 2, 1])

In [18]:
def sposob1():
  Z = np.array([1, 2, 3, 4])
  Z = Z[::-1]
  Z

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

 время работы решения способом 1: 3.7772000268887496e-05


**1.6**. Считайте 3 числа:

 n - количество элементов матрицы

 m и k - размеры матрицы (число строк и столбцов соответственно)

Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).
Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется
пустых мест.

**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.


In [ ]:
n=int(input())
m=int(input())
k=int(input())
Z = np.arange(n).reshape(m,k)
Z

6
2
3


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
n=int(input())
m=int(input())
k=int(input())

def sposob1():
  Z = np.arange(n).reshape(m,k)
  Z

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

6
2
3
 время работы решения способом 1: 3.207400004612282e-05


**1.7.** Дан вектор Z. Запишите в переменную NonZerros индексы ненулевых элементов.

**Примечание**. В этой задаче не нужно ничего считывать или выводить на печать. Матрица Z
уже готова, просто создайте NonZerros.


In [ ]:
NonZerros = np.nonzero([1, 0, 2, 0, 3, 0, 4])
NonZerros

(array([0, 2, 4, 6]),)

In [ ]:
def sposob1():
  NonZerros = np.nonzero([1, 0, 2, 0, 3, 0, 4])
  NonZerros

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

 время работы решения способом 1: 5.927600022914703e-05


**1.8.** Считайте число n. Создайте единичную матрицу размера n, сохраните результат в
переменную Z.

**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z

In [ ]:
#способ 1 - с NumPy
n = int(input('Введите число: '))
Z = np.eye(n)
Z

Введите число: 3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#способ 2 - без NumPy
n = int(input('Введите число: '))

Z = []
for i in range(n):
    Z.append([])
    for g in range(n):
        if i == g:
            Z[i].append(1) 
        else: 
            Z[i].append(0)    
for i in range(n):
    print(Z[i])

Введите число: 3
[1, 0, 0]
[0, 1, 0]
[0, 0, 1]


In [ ]:
n = int(input('Введите число: '))

def with_n(n):
  Z = np.eye(n)

def without_n(n):
  Z = []
  for i in range(n):
      Z.append([])
      for g in range(n):
          if i == g:
              Z[i].append(1) 
          else: 
            Z[i].append(0)


if __name__ == '__main__':
  start_time = timeit.default_timer()
  with_n(n)
  range_time_1 = timeit.default_timer() - start_time

  start_time = timeit.default_timer()
  without_n(n)
  arange_time_1 = timeit.default_timer() - start_time

print(f' время работы решения задачи с numpy: {range_time_1}')
print(f' время работы решения задачи без numpy: {arange_time_1}')

#Вывод: если размер матрицы небольшой, быстрее делать через Python, и наоборот

Введите число: 3
 время работы решения задачи с numpy: 4.9670000407786574e-05
 время работы решения задачи без numpy: 1.0240999472443946e-05


**1.9** Считайте 3 числа: n, m, l.. Зафиксируйте значение генератора случайных чисел Numpy
с помощью numpy.random.seed(42) . Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и
сохраните результат в переменную Z.

**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

In [ ]:
n = int(input())
m = int(input())
l = int(input())
np.random.seed(42)
Z = np.random.random((n,m,l))
Z

2
2
2


array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848]],

       [[0.15601864, 0.15599452],
        [0.05808361, 0.86617615]]])

In [ ]:
n = int(input())
m = int(input())
l = int(input())

def sposob1():
  np.random.seed(42)
  Z = np.random.random((n,m,l))
  Z

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

2
2
2
 время работы решения способом 1: 4.9405000027036294e-05


**1.10.** Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с
помощью numpy.random.seed(42). Создайте матрицу n*m из случайных чисел (от 0 до 1).

Выведите на печать значение минимального и максимального чисел в получившейся
матрице (каждое с новой строки).

In [ ]:
n=int(input())
m=int(input())
np.random.seed(42)
Z=np.random.random((n,m))
print(Z.min())
print(Z.max())

10
10
0.005522117123602399
0.9868869366005173


In [ ]:
n=int(input())
m=int(input())

def sposob1():
  np.random.seed(42)
  Z=np.random.random((n,m))
print(Z.min())
print(Z.max())

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

10
10
0.005522117123602399
0.9868869366005173
 время работы решения способом 1: 0.00011330699999234639


**1.11.** Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с
помощью numpy.random.seed(42).Создайте матрицу n*m из случайных чисел (от 0 до 1).

Выведите на печать значение среднего для всей матрицы.

In [ ]:
n=int(input())
m=int(input())
np.random.seed(42)
Z=np.random.random((n,m))
print(Z.mean())

30
30
0.4923750160905882


In [ ]:
n=int(input())
m=int(input())

def sposob1():
  np.random.seed(42)
  Z=np.random.random((n,m))
print(Z.mean())

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

30
30
0.4923750160905882
 время работы решения способом 1: 0.0009485139999014791


**1.12.** Переменные A и B содержат по numpy вектору. Найдите их скалярное произведение и
сохраните в переменную Z.
A и B могут содержать как int, так и float.

**Примечание.** В этой задаче не нужно ничего выводить на печать. Только создать Z.

In [ ]:
A = np.array(list(map(float, input().split()))) 
B = np.array(list(map(float, input().split()))) 
Z = np.dot(A, B)
Z

1.5 2.5 3.5
4 5 6


39.5

In [ ]:
A = np.array(list(map(float, input().split()))) 
B = np.array(list(map(float, input().split()))) 

def sposob1():
  Z = np.dot(A, B)
  Z

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

1.5 2.5 3.5
4 5 6
 время работы решения способом 1: 3.4280999898328446e-05


**1.13**. Даны 2 матрицы: A и B. Найдите произведение матриц и сохраните его в переменную Z.
Если найти произведение матриц невозможно, то запишите в Z строку:
Упс! Что-то пошло не так...

**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать Z.

In [ ]:
A = np.array([
 [1, 2, 3],
 [4, 5, 6]
])
B = np.array([
 [11.5],
 [12.5],
 [13.5]
])
try:
  Z = np.dot(A, B)
  print(Z)
except:
  print("Упс! Что-то пошло не так...")

[[ 77. ]
 [189.5]]


In [ ]:
A = np.array([
 [1, 2, 3],
 [4, 5, 6]
])
B = np.array([
 [11.5, 12.5, 13.5]
])
try:
  Z = np.dot(A, B)
  print(Z)
except:
  print("Упс! Что-то пошло не так...")

Упс! Что-то пошло не так...


In [ ]:
def sposob1():
  try:
    Z = np.dot(A, B)
    print(Z)
  except:
    print("Упс! Что-то пошло не так...")

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

Упс! Что-то пошло не так...
 время работы решения способом 1: 0.00020430100084922742


**1.14**. Поменяйте знак всех чисел из интервала (3; 9), хранящихся в векторе Z.

**Примечание**. В этой задаче не нужно ничего выводить на печать. Только заменить некоторые
элементы Z.

In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 9)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [ ]:
def sposob1():
  Z = np.arange(11)
  Z[(3 < Z) & (Z < 9)] *= -1
  Z

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

 время работы решения способом 1: 0.0009778809999261284


**1.15.** Подсчитать произведение ненулевых элементов на диагонали прямоугольной
матрицы. Для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [ ]:
#способ 1
X = np.diag(np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]), k=0)
NonZerros=np.nonzero(X)
X=X[NonZerros]
X=X.prod()
print(X)

3


In [ ]:
#способ 2
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print(np.prod(np.diag(X)[np.diag(X)!=0]))

3


In [ ]:
def sposob1():
  X = np.diag(np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]))
  NonZerros=np.nonzero(X)
  X=X[NonZerros]
  X=X.prod()
  print(X)

def sposob2():
  X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
  print(np.prod(np.diag(X)[np.diag(X)!=0]))

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time

  start_time = timeit.default_timer()
  sposob2()
  arange_time_1 = timeit.default_timer() - start_time

print(f' время работы решения способом 1: {range_time_1}')
print(f' время работы решения cпособом 2: {arange_time_1}')

3
3
 время работы решения способом 1: 0.0013721000004807138
 время работы решения cпособом 2: 0.0006875460003357148


**1.16.** Считайте число n. Создайте в переменной Z Numpy вектор из нулей длины n.

**Примечание.** В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.


In [10]:
n = int(input())
Z = np.zeros(n)
Z

5


array([0., 0., 0., 0., 0.])

In [12]:
n = int(input())
Z = ''
Z += '['
while n > 0:
  Z += '0. '
  n -= 1
Z = Z[0:-1]
Z += ']'
Z

5


'[0. 0. 0. 0. 0.]'

In [4]:
n = int(input())

def with_n(n):
  Z = np.zeros(n)
  return Z


def without_n(n):
  Z = ''
  Z += '['
  while n > 0:
    Z += '0. '
    n -= 1
  Z = Z[0:-1]
  Z += ']'
  return Z


if __name__ == '__main__':
  start_time = timeit.default_timer()
  with_n(n)
  range_time_1 = timeit.default_timer() - start_time

  start_time = timeit.default_timer()
  without_n(n)
  arange_time_1 = timeit.default_timer() - start_time

print(f' время работы решения задачи с numpy: {range_time_1}')
print(f' время работы решения задачи без numpy: {arange_time_1}')

5
 время работы решения задачи с numpy: 2.92259999810085e-05
 время работы решения задачи без numpy: 3.7800000143306534e-06


**1.17**. Посчитайте размер матрицы Z в байтах и выведите его на печать. Чтобы узнать
размер (в байтах) 1 элемента матрицы используйте
атрибут https://docs.scipy.org/doc/numpy1.15.1/reference/generated/numpy.ndarray.itemsize.html


**Примечание**. В этой задаче не нужно ничего считывать - матрица Z уже заполнена.

In [13]:
Z=np.zeros((10,10))
print(Z.nbytes)

800


In [14]:
Z=np.zeros((10,10))
print(Z.itemsize*Z.size)

800


In [5]:
def sposob1():
  Z=np.zeros((10,10))
  print(Z.nbytes)

def sposob2():
  Z=np.zeros((10,10))
  print(Z.itemsize*Z.size)

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time

  start_time = timeit.default_timer()
  sposob2()
  arange_time_1 = timeit.default_timer() - start_time

print(f' время работы решения способом 1: {range_time_1}')
print(f' время работы решения cпособом 2: {arange_time_1}')

800
800
 время работы решения способом 1: 0.0015519969999786554
 время работы решения cпособом 2: 0.00043537200008358923


**1.18.** Считайте 2 числа:


*   n - размер Numpy вектора
*   x - координата элемента вектора, который должен быть равен 1.

Остальные элементы вектора
должны быть равны 0. Сохраните вектор в переменную Z.

**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.

In [7]:
#способ 1
n=int(input())
x=int(input())
Z = np.zeros(n)
Z[x-1]=1
Z

10
4


array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [8]:
#способ 2
n=int(input())
x=int(input())
Z = np.zeros(n-1)
Z = np.insert(Z, x-1, 1)
Z

10
4


array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [6]:
n=int(input())
x=int(input())

def sposob1():
  Z = np.zeros(n)
  Z[x-1]=1
  Z

def sposob2():
  Z = np.zeros(n-1)
  Z = np.insert(Z, x-1, 1)
  Z

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time

  start_time = timeit.default_timer()
  sposob2()
  arange_time_1 = timeit.default_timer() - start_time

print(f' время работы решения способом 1: {range_time_1}')
print(f' время работы решения cпособом 2: {arange_time_1}')

10
4
 время работы решения способом 1: 7.176600001912448e-05
 время работы решения cпособом 2: 0.00022900200019648764


**1.19**. Считайте 2 числа n, m. Создайте вектор Z состоящий из чисел от n до m с шагом 1.

**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать вектор Z.


In [15]:
n=int(input())
m=int(input())
Z = np.arange(n, m+1, 1)
Z

10
50


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [16]:
n=int(input())
m=int(input())

def sposob1():
  Z = np.arange(n, m+1, 1)
  Z

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

10
50
 время работы решения способом 1: 0.00010038500022346852


**1.20**. Дан вектор Z. "Разверните" его.

**Примечание**. В этой задаче не нужно ничего выводить на печать или считывать. Только
развернуть уже созданный вектор Z.


In [19]:
Z = np.array([1, 2, 3, 4])
Z = Z[::-1]
Z

array([4, 3, 2, 1])

In [ ]:
def sposob1():
  Z = np.array([1, 2, 3, 4])
  Z = Z[::-1]
  Z

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

**1.21**. Считайте 3 числа:
 n - количество элементов матрицы
 m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).
Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется
пустых мест.


**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

In [34]:
n = int(input('Число: '))
m, k = map(int, input('Размер: ').split())

Z = np.arange(n).reshape(m, k)
Z

Число: 6
Размер: 2 3


array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
n = int(input('Число: '))
m, k = map(int, input('Размер: ').split())

def without_num(n, m, k):
    Z = []
    count = 0
    for i in range(m):
        Z.append([])
        for j in range(k):
            Z[i].append(count)
            count += 1


def with_num(n, m, k):
    Z = np.arange(n).reshape(m, k)

if __name__ == '__main__':
    if m * k == n:
        start_time = timeit.default_timer()
        with_num(n, m, k)
        time_1 = timeit.default_timer() - start_time
        start_time = timeit.default_timer()
        without_num(n, m, k)
        time_2 = timeit.default_timer() - start_time

        print('Время работы с NumPy: ', time_1)
        print('Время работы без NumPy: ', time_2)

Число: 6
Размер: 2 3
Время работы с NumPy:  3.860700053337496e-05
Время работы без NumPy:  8.518999493389856e-06


**1.22**. Дан вектор Z. Запишите в переменную NonZerros индексы ненулевых элементов.
Используйте
функцию https://docs.scipy.org/doc/numpy1.15.0/reference/generated/numpy.nonzero.html

**Примечание**. В этой задаче не нужно ничего считывать или выводить на печать. Матрица Z
уже готова, просто создайте NonZerros.


In [40]:
#способ 1
nonzero=[]
Z=[1, 0, 2, 0, 3, 0, 4]
for i in Z:
  if i==0:
   pass
  else:
    nonzero.append(Z.index(i))
print(nonzero)


[0, 2, 4, 6]


In [39]:
#способ 2
Z=np.array([1, 0, 2, 0, 3, 0, 4])
np.nonzero(Z)

(array([0, 2, 4, 6]),)

In [42]:
def without_num():
    nonzero=[]
    Z=[1, 0, 2, 0, 3, 0, 4]
    for i in Z:
      if i==0:
       pass
    else:
      nonzero.append(Z.index(i))



def with_num():
    Z=np.array([1, 0, 2, 0, 3, 0, 4])
    np.nonzero(Z)

if __name__ == '__main__':
        start_time = timeit.default_timer()
        without_num()
        time_1 = timeit.default_timer() - start_time
        start_time = timeit.default_timer()
        with_num()
        time_2 = timeit.default_timer() - start_time

        print('Время работы без NumPy: ', time_1)
        print('Время работы с NumPy: ', time_2)

Время работы без NumPy:  3.4869999581133015e-06
Время работы с NumPy:  3.689200002554571e-05


**1.23.** Считайте число n. Создайте единичную матрицу размера n, сохраните результат в
переменную Z.

**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

In [43]:
#способ 1 - с NumPy
n = int(input('Введите число: '))
Z = np.eye(n)
Z

Введите число: 3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
#способ 2 - без NumPy
n = int(input('Введите число: '))

Z = []
for i in range(n):
    Z.append([])
    for g in range(n):
        if i == g:
            Z[i].append(1) 
        else: 
            Z[i].append(0)    
for i in range(n):
    print(Z[i])

Введите число: 3
[1, 0, 0]
[0, 1, 0]
[0, 0, 1]


In [46]:
n = int(input('Введите число: '))

def with_n(n):
  Z = np.eye(n)

def without_n(n):
  Z = []
  for i in range(n):
      Z.append([])
      for g in range(n):
          if i == g:
              Z[i].append(1) 
          else: 
            Z[i].append(0)


if __name__ == '__main__':
  start_time = timeit.default_timer()
  with_n(n)
  range_time_1 = timeit.default_timer() - start_time

  start_time = timeit.default_timer()
  without_n(n)
  arange_time_1 = timeit.default_timer() - start_time

print(f' время работы решения задачи с numpy: {range_time_1}')
print(f' время работы решения задачи без numpy: {arange_time_1}')

#Вывод: если размер матрицы небольшой, быстрее делать через Python, и наоборот

Введите число: 3
 время работы решения задачи с numpy: 5.353399956220528e-05
 время работы решения задачи без numpy: 8.680000064487103e-06


**1.24**. Считайте 3 числа: n, m, l.. Зафиксируйте значение генератора случайных чисел
Numpy с помощью numpy.random.seed(42) . Создайте матрицу n*m*l из случайных чисел (от 0
до 1) и сохраните результат в переменную Z.


**Примечание**. В этой задаче не нужно ничего выводить на печать. Только создать матрицу Z.

In [47]:
n = int(input())
m = int(input())
l = int(input())

np.random.seed(42)
Z = np.random.random((n,m,l))
Z

2
2
2


array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848]],

       [[0.15601864, 0.15599452],
        [0.05808361, 0.86617615]]])

In [48]:
n = int(input())
m = int(input())
l = int(input())

def sposob1():
  np.random.seed(42)
  Z = np.random.random((n,m,l))
  Z

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

2
2
2
 время работы решения способом 1: 9.083499935513828e-05


**1.25.** Считайте 2 числа: n, m. Зафиксируйте значение генератора случайных чисел Numpy с
помощью numpy.random.seed(42). Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение минимального и максимального чисел в получившейся
матрице (каждое с новой строки).

In [49]:
n=int(input())
m=int(input())

np.random.seed(42)
Z=np.random.random((n,m))
print(Z.min())
print(Z.max())

10
10
0.005522117123602399
0.9868869366005173


In [50]:
n=int(input())
m=int(input())

def sposob1():
  np.random.seed(42)
  Z=np.random.random((n,m))
print(Z.min())
print(Z.max())

if __name__ == '__main__':
  start_time = timeit.default_timer()
  sposob1()
  range_time_1 = timeit.default_timer() - start_time
print(f' время работы решения способом 1: {range_time_1}')

10
10
0.005522117123602399
0.9868869366005173
 время работы решения способом 1: 4.5621000026585534e-05
